# These are supported funding model platforms
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GLQ52YVTN24CN&source=url
# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
